[package]
name = "ssd1322"
description = "SPI driver for the SSD1322 OLED display controller"
version = "0.3.0"
authors = ["Kyle Schaffrick <kyle@raidi.us>"]
edition = "2018"
keywords = ["no-std", "ssd1322", "oled", "embedded", "embedded-hal-driver"]
repository = "https://github.com/edarc/ssd1322"
readme = "README.md"
license = "MIT OR Apache-2.0"
exclude = [
	".gitignore",
	"ferris-on-nhd.jpg",
]

[dependencies]
display-interface = { git = "https://github.com/therealprof/display-interface.git", commit = "9b915f93e8665f56b47f11d4fe28c92c1db514bb" } # 0.5
maybe-async-cfg = "0.2"

[dependencies.itertools]
version = "0.7"
default-features = false

[features]
default = ["async"]
async = []
